### PR TITLE
Fix #219 ("initializer" => "initialize" and related)

### PR DESCRIPTION
**Pull request by tjcrowder**
Fixes #219 ("initializer" => "initialize" and [[Initializer]] => [[Init…ialize]] consistently)

### CODE REVIEW

**Comment by littledan** [comment]
Happy to commit this together with the other renamings together.

**Comment by tjcrowder** [comment]
Should have those ready in the next hour or two. :-)

**Review by littledan — APPROVED** [review]

**Comment by littledan** [comment]
Could you rebase this patch?

**Comment by littledan** [comment]
Well, I just rebased it myself, since I was so excited to merge it!

**Comment by tjcrowder** [comment]
Beat me to it!

**Pull request merged**
