### PR TITLE
Revert "Normative: Remove class decorator access to private names"

### PR DESCRIPTION
**Pull request by littledan**
This reverts PR #151.

Rationale in https://github.com/tc39/proposal-decorators/issues/133#issuecomment-452676378

### CODE REVIEW

**Review by nicolo-ribaudo — APPROVED** [review]

**Comment by littledan** [comment]
We'll have to do some more thinking and talking to finalize this decision, but merging the PR in order to represent my best understanding of our current champion group preferences.

**Comment by ljharb** [comment]
This is a pretty large change to rapidly merge in without having discussed it in a decorators call (unless i missed it).

**Comment by littledan** [comment]
We'll have a call next week. Let me know if you didn't get an invite. We've been discussing this on various threads, and the proposal is still at Stage 2, so still making these sorts of changes.

**Comment by ljharb** [comment]
Unfortunately I have a conflict next week, so I can't make it (i was able to make it yesterday).

I realize these sorts of changes can still happen in stage 2, but merging a large and potentially controversial decision after 2 hours feels like shutting down discussion and not seeking feedback even from the regular discussion group.

**Comment by littledan** [comment]
I would really like to continue to discuss this, before the TC39 meeting and, if the champion group decides strongly on this version, at the meeting. I'm working on a bunch of patches, and it's annoying to work through all the conflicts, so I wanted to land one alternative at ToT, and none have full consensus. I see the alternative to this patch to be completely removing elements, in favor of class decorators adding extras. We're discussing whether this would be a good idea in a few threads, such as https://github.com/tc39/proposal-decorators/issues/192 . I don't see the ToT before this patch as at all viable.

**Pull request merged**
