### PR TITLE
2nd attempt to merge documentation update.

### PR DESCRIPTION
**Pull request by rdking**
1st attempt likely failed due to it being from a branch of my fork.

### CODE REVIEW

**Comment by rdking** [comment]
Can someone point out what it will take to get this to merge properly? I'm at a loss.

**Comment by ljharb** [comment]
It’s just test failures; it’ll merge fine. No need to make additional PRs.

**Comment by rdking** [comment]
Thanks. I'll leave it alone then.

**Comment by littledan** [comment]
Yeah, the failures are just because I set up the CI in a rough way that I haven't gotten around to fixing yet.

**Comment by littledan** [comment]
I proposed the word "hidden" before, and my memory was that other folks didn't like it. Also, I'd prefer if the definition of unobservable could be a little less ad-hoc than specifically calling out Function.prototype.toString.

**Comment by rdking** [comment]
I can understand that, but in the context of the private fields proposal, it's a more accurate term for what TC39 has decided it wants. To anything outside the scope of the declaring class, a private field does not appear to even exist. "Hidden" suits that pretty well. If you can find a way to say that anything exposing any portion of the source code is excluded from consideration for the "unobservable" portion, I don't mind changing it.

**Comment by ljharb** [comment]
The term "hidden" implies to me that it could be found, which wouldn't thus meet the criteria here :-/

**Comment by thomassuckow** [comment]
Could you just state you define "private" to mean: ...

It seems convoluted that the title of the section is "Private fields and methods". Then states that we used to say "hard private" (despite only the most intimately familiar will remember that usage). Then basically states that we pulled the word "hidden" out of a hat because we can't use private despite the fields and methods ARE private and we define it however we like.

It really seems like you could just say:

## Private fields and methods

In the context of this proposal, we define *private* as follows:
> A class element with the syntax `#name` is considered *private* because it is:
> * *inaccessible*, which makes it unavailable for reads and writes, except to those granted explicit access to it, and     
> * *unobservable*, which makes its presence completely undetectable, except via source code or `Function.prototype.toString`.

**Comment by littledan** [comment]
Closing re https://github.com/tc39/proposal-decorators/pull/159#issuecomment-434491104 .

**Pull request closed without merging**
