### PR TITLE
This makes "hidden" perfectly clear, including the exclusions.

### PR DESCRIPTION
**Pull request by rdking**

### CODE REVIEW

**Review by ljharb — APPROVED** [review]
Thanks, this is much clearer to me.

**Comment by rdking** [comment]
ok. What do I need to do to get this PR to merge?

**Review by nicolo-ribaudo — APPROVED** [review]

**Comment by littledan** [comment]
I explained on other threads why I am hesitant to use hidden and these two bullet points.

**Comment by littledan** [comment]
See https://github.com/tc39/proposal-decorators/pull/160

**Comment by littledan** [comment]
Closing re https://github.com/tc39/proposal-decorators/pull/159#issuecomment-434491104

**Pull request closed without merging**
