### PR TITLE
Require decorators before 'export' keyword

### LINKED ISSUE #69: @deco before or after export keyword?
```js
@deco
export class A {}
```
or
```js
export @deco class A {}
```
or allow both?

### PR DESCRIPTION
**Pull request by rbuckton**
Fixes #69

### CODE REVIEW

**Comment by ljharb** [comment]
fwiw I really don't like this change; I look forward to discussing it at the meeting.

**Review by littledan — CHANGES_REQUESTED** [review]
I think lookaheads should be used as a last resort. In the "export Expression" grammar, it's necessary because it's cutting down into PrimaryExpression, but here it looks like a simpler refactoring could eliminate the three lookaheads here. Could ClassDeclaration be factored into two productions, with the inner one not having decorators?

**Comment by rbuckton** [comment]
A production parameter would probably be better than adding more productions.

**Comment by rbuckton** [comment]
I've switched this to using a `Decorators` parameter, but the spec emit will be broken until https://github.com/bterlson/ecmarkup/pull/142 lands.

**Review by littledan — APPROVED** [review]
Good idea to use a parameter; this came out cleaner than I expected.

**Comment by rbuckton** [comment]
I've updated the minimum version of ecmarkup in the package.json to correctly emit the amended productions.

**Comment by rbuckton** [comment]
@littledan since the PR builds don't work for me due to the publishing key, is there a separate process that will run following this commit to update the spec docs?

**Comment by littledan** [comment]
@rbuckton Looks like Travis-CI built it well and it's reflected in what's up. Sorry that it's a bit hacky and doesn't work on branches; not sure how it should be set up.

**Comment by rbuckton** [comment]
As an alternative, take a look at how I've set up https://github.com/tc39/proposal-throw-expressions. I have the GitHub pages feature set up to serve from /docs in master. I haven't set up any kind of CI, however.

**Pull request merged**
