### PR TITLE
Normative: Renamings in decorator descriptors

### PR DESCRIPTION
**Pull request by littledan**
Resolves #173 

See individual commit messages for details.

### CODE REVIEW

**Comment by littledan** [comment]
cc @nicolo-ribaudo @tjcrowder @Lodin @pabloalmunia

**Comment by ljharb** [comment]
We may want to consider the interaction of “hook” with the upcoming React feature.

**Comment by tjcrowder** [comment]
@ljharb - It's a really generic term, I don't think there's a problem there. But there's always...`"callback"`. 😁 (Or `"phase"`?)

**Comment by ljharb** [comment]
I think hook is the best we’ve come up with so far, just wanted to mention the overlap :-)

**Review by pabloalmunia — APPROVED** [review]

**Comment by littledan** [comment]
I guess react hooks don't ever use the term "hook" in source code, so maybe we're good here. Let's go with "hook" for now, and we can reconsider it in future issues.

**Pull request merged**
